import BottomNav from "@/components/custom-ui/common/BottomNav";
import LeftSidebar from "@/components/custom-ui/common/LSideBar";
import Navbar from "@/components/custom-ui/common/Navbar";
import RightSidebar from "@/components/custom-ui/common/RSidebar";
import Providers from "@/components/custom-ui/Provider";
import { Toaster } from "@/components/ui/toaster";
import { ClerkProvider } from "@clerk/nextjs";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <Providers>
        <html lang="en">
          <body className={`${inter.className} w-full h-screen`} suppressHydrationWarning={true}>
            {/* <Navbar />

              <main className="flex flex-row">
                <LeftSidebar /> */}
             {children}

            {/* @ts-ignore */}
            {/* <RightSidebar /> */}
            {/* </main>

              <BottomNav /> */}
            <Toaster />
          </body>
        </html>
      </Providers>
    </ClerkProvider>
  );
}
